#define KS_SPACE 	 0x20
#define KS_EXCLAM 	 0x21
#define KS_QUOTEDBL 	 0x22
#define KS_NUMBERSIGN 	 0x23
#define KS_DOLLAR 	 0x24
#define KS_PERCENT 	 0x25
#define KS_AMPERSAND 	 0x26
#define KS_APOSTROPHE 	 0x27
#define KS_PARENLEFT 	 0x28
#define KS_PARENRIGHT 	 0x29
#define KS_ASTERISK 	 0x2A
#define KS_PLUS 	 0x2B
#define KS_COMMA 	 0x2C
#define KS_MINUS 	 0x2D
#define KS_PERIOD 	 0x2E
#define KS_SLASH 	 0x2F
#define KS_0 	 0x30
#define KS_1 	 0x31
#define KS_2 	 0x32
#define KS_3 	 0x33
#define KS_4 	 0x34
#define KS_5 	 0x35
#define KS_6 	 0x36
#define KS_7 	 0x37
#define KS_8 	 0x38
#define KS_9 	 0x39
#define KS_COLON 	 0x3A
#define KS_SEMICOLON 	 0x3B
#define KS_LESS 	 0x3C
#define KS_EQUAL 	 0x3D
#define KS_GREATER 	 0x3E
#define KS_QUESTION 	 0x3F
#define KS_AT 	 0x40
#define KS_BRACKETLEFT 	 0x5B
#define KS_BACKSLASH 	 0x5C
#define KS_BRACKETRIGHT 	 0x5D
#define KS_ASCIICIRCUM 	 0x5E
#define KS_UNDERSCORE 	 0x5F
#define KS_GRAVE 	 0x60
#define KS_BRACELEFT 	 0x7B
#define KS_BAR 	 0x7C
#define KS_BRACERIGHT 	 0x7D
#define KS_ASCIITILDE 	 0x7E
#define KS_NOBREAKSPACE 	 0xA0
#define KS_EXCLAMDOWN 	 0xA1
#define KS_CENT 	 0xA2
#define KS_STERLING 	 0xA3
#define KS_CURRENCY 	 0xA4
#define KS_YEN 	 0xA5
#define KS_BROKENBAR 	 0xA6
#define KS_SECTION 	 0xA7
#define KS_DIAERESIS 	 0xA8
#define KS_COPYRIGHT 	 0xA9
#define KS_ORDFEMININE 	 0xAA
#define KS_GUILLEMOTLEFT 	 0xAB
#define KS_NOTSIGN 	 0xAC
#define KS_HYPHEN 	 0xAD
#define KS_REGISTERED 	 0xAE
#define KS_MACRON 	 0xAF
#define KS_DEGREE 	 0xB0
#define KS_PLUSMINUS 	 0xB1
#define KS_TWOSUPERIOR 	 0xB2
#define KS_THREESUPERIOR 	 0xB3
#define KS_ACUTE 	 0xB4
#define KS_MU 	 0xB5
#define KS_PARAGRAPH 	 0xB6
#define KS_PERIODCENTERED 	 0xB7
#define KS_CEDILLA 	 0xB8
#define KS_ONESUPERIOR 	 0xB9
#define KS_MASCULINE 	 0xBA
#define KS_GUILLEMOTRIGHT 	 0xBB
#define KS_ONEQUARTER 	 0xBC
#define KS_ONEHALF 	 0xBD
#define KS_THREEQUARTERS 	 0xBE
#define KS_QUESTIONDOWN 	 0xBF
#define KS_AGRAVE 	 0xC0
#define KS_AACUTE 	 0xC1
#define KS_ACIRCUMFLEX 	 0xC2
#define KS_ATILDE 	 0xC3
#define KS_ADIAERESIS 	 0xC4
#define KS_ARING 	 0xC5
#define KS_AE 	 0xC6
#define KS_CCEDILLA 	 0xC7
#define KS_EGRAVE 	 0xC8
#define KS_EACUTE 	 0xC9
#define KS_ECIRCUMFLEX 	 0xCA
#define KS_EDIAERESIS 	 0xCB
#define KS_IGRAVE 	 0xCC
#define KS_IACUTE 	 0xCD
#define KS_ICIRCUMFLEX 	 0xCE
#define KS_IDIAERESIS 	 0xCF
#define KS_ETH 	 0xD0
#define KS_NTILDE 	 0xD1
#define KS_OGRAVE 	 0xD2
#define KS_OACUTE 	 0xD3
#define KS_OCIRCUMFLEX 	 0xD4
#define KS_OTILDE 	 0xD5
#define KS_ODIAERESIS 	 0xD6
#define KS_MULTIPLY 	 0xD7
#define KS_OSLASH 	 0xD8
#define KS_UGRAVE 	 0xD9
#define KS_UACUTE 	 0xDA
#define KS_UCIRCUMFLEX 	 0xDB
#define KS_UDIAERESIS 	 0xDC
#define KS_YACUTE 	 0xDD
#define KS_THORN 	 0xDE
#define KS_SSHARP 	 0xDF
#define KS_AGRAVE 	 0xE0
#define KS_AACUTE 	 0xE1
#define KS_ACIRCUMFLEX 	 0xE2
#define KS_ATILDE 	 0xE3
#define KS_ADIAERESIS 	 0xE4
#define KS_ARING 	 0xE5
#define KS_AE 	 0xE6
#define KS_CCEDILLA 	 0xE7
#define KS_EGRAVE 	 0xE8
#define KS_EACUTE 	 0xE9
#define KS_ECIRCUMFLEX 	 0xEA
#define KS_EDIAERESIS 	 0xEB
#define KS_IGRAVE 	 0xEC
#define KS_IACUTE 	 0xED
#define KS_ICIRCUMFLEX 	 0xEE
#define KS_IDIAERESIS 	 0xEF
#define KS_ETH 	 0xF0
#define KS_NTILDE 	 0xF1
#define KS_OGRAVE 	 0xF2
#define KS_OACUTE 	 0xF3
#define KS_OCIRCUMFLEX 	 0xF4
#define KS_OTILDE 	 0xF5
#define KS_ODIAERESIS 	 0xF6
#define KS_DIVISION 	 0xF7
#define KS_OSLASH 	 0xF8
#define KS_UGRAVE 	 0xF9
#define KS_UACUTE 	 0xFA
#define KS_UCIRCUMFLEX 	 0xFB
#define KS_UDIAERESIS 	 0xFC
#define KS_YACUTE 	 0xFD
#define KS_THORN 	 0xFE
#define KS_YDIAERESIS 	 0xFF
#define KS_AOGONEK 	 0x1A1
#define KS_BREVE 	 0x1A2
#define KS_LSTROKE 	 0x1A3
#define KS_LCARON 	 0x1A5
#define KS_SACUTE 	 0x1A6
#define KS_SCARON 	 0x1A9
#define KS_SCEDILLA 	 0x1AA
#define KS_TCARON 	 0x1AB
#define KS_ZACUTE 	 0x1AC
#define KS_HOME 	 0xFF50
#define KS_LEFT 	 0xFF51
#define KS_UP 	 0xFF52
#define KS_RIGHT 	 0xFF53
#define KS_DOWN 	 0xFF54
#define KS_PRIOR 	 0xFF55
#define KS_NEXT 	 0xFF56
#define KS_END 	 0xFF57
#define KS_BEGIN 	 0xFF58
#define KS_WIN_L 	 0xFF5B
#define KS_WIN_R 	 0xFF5C
#define KS_F1 	 0xFFBE
#define KS_F2 	 0xFFBF
#define KS_F3 	 0xFFC0
#define KS_F4 	 0xFFC1
#define KS_F5 	 0xFFC2
#define KS_F6 	 0xFFC3
#define KS_F7 	 0xFFC4
#define KS_F8 	 0xFFC5
#define KS_F9 	 0xFFC6
#define KS_F10 	 0xFFC7
#define KS_F11 	 0xFFC8
#define KS_F12 	 0xFFC9
#define KS_F13 	 0xFFCA
#define KS_F14 	 0xFFCB
#define KS_F15 	 0xFFCC
#define KS_F16 	 0xFFCD
#define KS_F17 	 0xFFCE
#define KS_F18 	 0xFFCF
#define KS_F19 	 0xFFD0
#define KS_F20 	 0xFFD1
#define KS_F21 	 0xFFD2
#define KS_F22 	 0xFFD3
#define KS_F23 	 0xFFD4
#define KS_F24 	 0xFFD5
#define KS_F25 	 0xFFD6
#define KS_F26 	 0xFFD7
#define KS_F27 	 0xFFD8
#define KS_F28 	 0xFFD9
#define KS_F29 	 0xFFDA
#define KS_F30 	 0xFFDB
#define KS_F31 	 0xFFDC
#define KS_F32 	 0xFFDD
#define KS_F33 	 0xFFDE
#define KS_F34 	 0xFFDF
#define KS_F35 	 0xFFE0
#define KS_SHIFT_L 	 0xFFE1
#define KS_SHIFT_R 	 0xFFE2
#define KS_CONTROL_L 	 0xFFE3
#define KS_CONTROL_R 	 0xFFE4
#define KS_CAPS_LOCK 	 0xFFE5
#define KS_SHIFT_LOCK 	 0xFFE6
#define KS_META_L 	 0xFFE7
#define KS_META_R 	 0xFFE8
#define KS_ALT_L 	 0xFFE9
#define KS_ALT_R 	 0xFFEA
#define KS_SUPER_L 	 0xFFEB
#define KS_SUPER_R 	 0xFFEC
#define KS_HYPER_L 	 0xFFED
#define KS_HYPER_R 	 0xFFEE
#define KS_DELETE 	 0xFFFF
#define KS_XF86AUDIOLOWERVOLUME 	 0x1008FF11
#define KS_XF86AUDIOMUTE 	 0x1008FF12
#define KS_XF86AUDIORAISEVOLUME 	 0x1008FF13
#define KS_XF86AUDIOPLAY 	 0x1008FF14
#define KS_XF86AUDIOSTOP 	 0x1008FF15
#define KS_XF86AUDIOPREV 	 0x1008FF16
#define KS_XF86AUDIONEXT 	 0x1008FF17
#define KS_KP_SPACE 	 0xFF80
#define KS_KP_TAB 	 0xFF89
#define KS_KP_ENTER 	 0xFF8D
#define KS_KP_F1 	 0xFF91
#define KS_KP_F2 	 0xFF92
#define KS_KP_F3 	 0xFF93
#define KS_KP_F4 	 0xFF94
#define KS_KP_HOME 	 0xFF95
#define KS_KP_LEFT 	 0xFF96
#define KS_KP_UP 	 0xFF97
#define KS_KP_RIGHT 	 0xFF98
#define KS_KP_DOWN 	 0xFF99
#define KS_KP_PRIOR 	 0xFF9A
#define KS_KP_NEXT 	 0xFF9B
#define KS_KP_END 	 0xFF9C
#define KS_KP_BEGIN 	 0xFF9D
#define KS_KP_INSERT 	 0xFF9E
#define KS_KP_DELETE 	 0xFF9F
#define KS_KP_MULTIPLY 	 0xFFAA
#define KS_KP_ADD 	 0xFFAB
#define KS_KP_SEPARATOR 	 0xFFAC
#define KS_KP_SUBTRACT 	 0xFFAD
#define KS_KP_DECIMAL 	 0xFFAE
#define KS_KP_DIVIDE 	 0xFFAF
#define KS_KP_0 	 0xFFB0
#define KS_KP_1 	 0xFFB1
#define KS_KP_2 	 0xFFB2
#define KS_KP_3 	 0xFFB3
#define KS_KP_4 	 0xFFB4
#define KS_KP_5 	 0xFFB5
#define KS_KP_6 	 0xFFB6
#define KS_KP_7 	 0xFFB7
#define KS_KP_8 	 0xFFB8
#define KS_KP_9 	 0xFFB9
#define KS_KP_EQUAL 	 0xFFBD
#define KS_BACKSPACE 	 0xFF08
#define KS_TAB 	 0xFF09
#define KS_LINEFEED 	 0xFF0A
#define KS_CLEAR 	 0xFF0B
#define KS_RETURN 	 0xFF0D
#define KS_PAUSE 	 0xFF13
#define KS_SCROLL_LOCK 	 0xFF14
#define KS_SYS_REQ 	 0xFF15
#define KS_ESCAPE 	 0xFF1B
